const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('jarvis', {
  sendMessage: (msg) => ipcRenderer.invoke('chat:send', msg),
  onStream: (cb) => ipcRenderer.on('chat:stream', (_, data) => cb(data)),
  onStatusMessage: (cb) => ipcRenderer.on('chat:status', (_, data) => cb(data)),
  onBusEvent: (cb) => ipcRenderer.on('bus:event', (_, data) => cb(data)),
  onConnectionStatus: (cb) => ipcRenderer.on('connection:status', (_, data) => cb(data)),
  loadChats: () => ipcRenderer.invoke('chat:load'),
  saveChat: (chat) => ipcRenderer.invoke('chat:save', chat),
  deleteChat: (chatPath) => ipcRenderer.invoke('chat:delete', chatPath),
  listProjects: () => ipcRenderer.invoke('projects:list'),
  createProject: (name, context) => ipcRenderer.invoke('projects:create', { name, context }),
  deleteProject: (name) => ipcRenderer.invoke('projects:delete', name),
  listProjectChats: (projectName) => ipcRenderer.invoke('projects:listChats', projectName),
  spawnAgent: (task) => ipcRenderer.invoke('agent:spawn', task),
  getConnectionStatus: () => ipcRenderer.invoke('connection:status'),
  minimize: () => ipcRenderer.invoke('window:minimize'),
  close: () => ipcRenderer.invoke('window:close'),
  removeAllListeners: (channel) => ipcRenderer.removeAllListeners(channel),
  readFile: (filePath) => ipcRenderer.invoke('file:read', filePath),
  listProjectFiles: (projectName) => ipcRenderer.invoke('project:listFiles', projectName),
  addProjectFile: (projectName, filePath) => ipcRenderer.invoke('project:addFile', { projectName, filePath }),
  removeProjectFile: (projectName, filename) => ipcRenderer.invoke('project:removeFile', { projectName, filename }),
  readProjectFile: (projectName, filename) => ipcRenderer.invoke('project:readFile', { projectName, filename }),
})
